### ISSUE TITLE
Implement AbstractNFFT.jl

### ISSUE THREAD

**Issue by tknopp** [jipolanco/NonuniformFFTs.jl#26]
Since there are multiple NFFT packages in Julia we developed a common API named AbstractNFFT.jl https://github.com/JuliaMath/NFFT.jl/tree/master/Wrappers

It would be great if you would consider implementing AbstractNFFT.jl which would allow others to use `NonuniformFFT.jl` as a drop in replacement for NFFT.jl.

For the other three packages (DUCC, NFFT3, FINUFFT) I created wrappers in NFFT.jl which is not ideal. The proper integration would be that `NonuniformFFT.jl` depends on `AbstractNFFT.jl`, which would be exactly the same as for all FFT packages.

Regarding the API you don't need to change your own API and can just provide both. But in principle the `AbstractNFFT.jl` API should be generic to also serve as the primary API. That was at least the design goal :-)

**Comment by jipolanco** [comment]
Thanks, it would definitely make sense for NonuniformFFTs.jl to implement the AbstractNFFT.jl interface, and I agree that this should be implemented within the NonuniformFFTs.jl package. I'll take a look at the docs and try to provide an AbstractNFFTs.jl interface.

**Comment by jipolanco** [comment]
So I think I got the interface working in #27.

It was a bit tricky to get it right because of the different conventions used in NFFT.jl and NonuniformFFTs.jl. So I decided that plans created via the AbstractNFFTs interface would follow the NFFT.jl conventions, which should allow to directly compare different packages using this interface. Plans created via the original interface will still follow the original conventions, in part for backwards compatibility and also because I find them more convenient for my own applications.

In particular there is a [new test](https://github.com/jipolanco/NonuniformFFTs.jl/pull/27/files#diff-351de6876ff980f5eb0b56765f5540a599c4315b3515a0f7a34a492cc376f997) which successfully verifies that the two packages give the same outputs when using the AbstractNFFTs interface.

I'd be happy to hear if you have any comments. And thanks for providing this interface, it really helps providing a common API allowing to easily switch between different packages.

**Comment by tknopp** [comment]
wow, that was very quick. I will give you feedback until next week!
And yes, accuracy verification is a strong point of the common interface, which helped me fixing quite some minor issue in NFFT.jl. The other aspect will be that you will get a detailed performance benchmark for free: https://juliamath.github.io/NFFT.jl/dev/performance/
I will include NonuniformFFTs.jl there as well. It helped me a lot to improve the performance of NFFT.jl

**Comment by tknopp** [comment]
I had a quick look and that looks pretty good. You already went for a proper implementation where your type directly inherits from the abstract type. This is in contrast to my wrapper approach. So well done!
What is still missing is the `plan_nfft` constructor. Similar to `AbstractFFT` it allows to create plans without the need to know which "backend" is used.

**Comment by jipolanco** [comment]
Thank you for your comments!

For now I didn't implement the `plan_nfft` constructor because it wasn't clear to me how it's supposed to be used. I mean, if both NFFT.jl and NonuniformFFTs.jl implement `plan_nfft(Array, k::Matrix{T}, N::NTuple{D,Int}; kwargs...)`, then I imagine there will be a conflict when both are loaded, as rightly pointed out in the docs. So a user willing to try out different implementations via `plan_nfft` cannot load multiple NFFT packages within the same Julia session? Then I guess this constructor should be used when one has chosen a "preferred" implementation, making it easy to switch to a different one later?
